		<!-- ============================================================= FOOTER ============================================================= -->
		
		<footer class="dark-bg">
			<div class="container inner">
				<div class="row">
					
					<div class="col-md-4 col-sm-6 inner">
						<h4>Who we are</h4>
						<a href="index.html"><img class="logo img-intext" src="<?php echo $TOP_DIR ?>/assets/images/logo-white.svg" alt=""></a>
						<p>We are building ways to safely exchange attributes about yourself online. You are in control of your credentials. Always.</p>
						<a href="./" class="txt-btn">More about us</a>
					</div><!-- /.col -->
					
					<div class="col-md-4 col-sm-6 inner">
						<h4>Specs</h4>
						
						<div class="row thumbs gap-xs">
														
							<div class="col-xs-6 thumb">
								<figure class="icon-overlay icn-link">
									<a href="/">Identity Credentials</a>
								</figure>
							</div><!-- /.thumb -->
						</div><!-- /.row -->
						<div class="row thumbs gap-xs">
							<div class="col-xs-6 thumb">
								<figure class="icon-overlay icn-link">
									<a href="/">HTTP Signatures</a>
								</figure>
							</div><!-- /.thumb -->
														
						</div><!-- /.row -->
					</div><!-- /.col -->
					
					
					<div class="col-md-4 col-sm-6 inner">
						<h4>Join us</h4>
						<p>There are many ways to help:</p>
						<ul class="contacts">
							<li><a href="http://www.w3.org/community/credentials/"><i class="icon-location contact"></i> Credentials Community Group @ W3C</a></li>
							<li><a href="http://lists.w3.org/Archives/Public/public-credentials/"><i class="icon-mail-1 contact"></i> public-credentials@w3.org</a></li>
						</ul><!-- /.contacts -->
					</div><!-- /.col -->
										
				</div><!-- /.row --> 
			</div><!-- .container -->
		  
			<div class="footer-bottom">
				<div class="container inner">
					<p class="pull-left">&copy; OCCG - CC0 - Public domain</p>
					<ul class="footer-menu pull-right">
						<li><a href="<?php echo $TOP_DIR ?>/">Home</a></li>
					</ul><!-- .footer-menu -->
				</div><!-- .container -->
			</div><!-- .footer-bottom -->
		</footer>
		
		<!-- ============================================================= FOOTER : END ============================================================= -->
		
		<!-- JavaScripts placed at the end of the document so the pages load faster -->
		<script src="<?php echo $TOP_DIR ?>/assets/js/jquery.min.js"></script>
		<script src="<?php echo $TOP_DIR ?>/assets/js/jquery.easing.1.3.min.js"></script>
		<script src="<?php echo $TOP_DIR ?>/assets/js/jquery.form.js"></script>
		<script src="<?php echo $TOP_DIR ?>/assets/js/jquery.validate.min.js"></script>
		<script src="<?php echo $TOP_DIR ?>/assets/js/bootstrap.min.js"></script>
		<script src="<?php echo $TOP_DIR ?>/assets/js/bootstrap-hover-dropdown.min.js"></script>
		<script src="<?php echo $TOP_DIR ?>/assets/js/skrollr.min.js"></script>
		<script src="<?php echo $TOP_DIR ?>/assets/js/skrollr.stylesheets.min.js"></script>
		<script src="<?php echo $TOP_DIR ?>/assets/js/waypoints.min.js"></script>
		<script src="<?php echo $TOP_DIR ?>/assets/js/waypoints-sticky.min.js"></script>
		<script src="<?php echo $TOP_DIR ?>/assets/js/owl.carousel.min.js"></script>
		<script src="<?php echo $TOP_DIR ?>/assets/js/jquery.isotope.min.js"></script>
		<script src="<?php echo $TOP_DIR ?>/assets/js/jquery.easytabs.min.js"></script>
		<script src="<?php echo $TOP_DIR ?>/assets/js/google.maps.api.v3.js"></script>
		<script src="<?php echo $TOP_DIR ?>/assets/js/viewport-units-buggyfill.js"></script>
		<script src="<?php echo $TOP_DIR ?>/assets/js/scripts.js"></script>		
	</body>
</html>
