<!DOCTYPE html>

<html lang="en">
  <head>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <title>Open Credentials</title>
    
    <!-- Bootstrap Core CSS -->
    <link href="<?php echo $TOP_DIR ?>/assets/css/bootstrap.min.css" rel="stylesheet">
    
    <!-- Customizable CSS -->
    <link href="<?php echo $TOP_DIR ?>/assets/css/main.css" rel="stylesheet" data-skrollr-stylesheet>
		<link href="<?php echo $TOP_DIR ?>/assets/css/purple.css" rel="stylesheet" title="Color">
    <link href="<?php echo $TOP_DIR ?>/assets/css/owl.carousel.css" rel="stylesheet">
    <link href="<?php echo $TOP_DIR ?>/assets/css/owl.transitions.css" rel="stylesheet">
    <link href="<?php echo $TOP_DIR ?>/assets/css/animate.min.css" rel="stylesheet">

    
    <!-- Fonts -->
    <link href="//fonts.googleapis.com/css?family=Lato:400,900,300,700" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,400italic,700italic" rel="stylesheet">
    
    <!-- Icons/Glyphs -->
    <link href="<?php echo $TOP_DIR ?>/assets/fonts/fontello.css" rel="stylesheet">
    
    <!-- Favicon -->
    <link rel="shortcut icon" href="<?php echo $TOP_DIR ?>/assets/images/favicon.ico">
    
    <!-- HTML5 elements and media queries Support for IE8 : HTML5 shim and Respond.js -->
    <!--[if lt IE 9]>
      <script src="<?php echo $TOP_DIR ?>/assets/js/html5shiv.js"></script>
      <script src="<?php echo $TOP_DIR ?>/assets/js/respond.min.js"></script>
    <![endif]-->
  </head>
  
  <body>
  
    
    <!-- ============================================================= HEADER ============================================================= -->
    
    <header>
      <div class="navbar">
        
        <div class="navbar-header">
          <div class="container">
            
            <!-- ============================================================= LOGO MOBILE ============================================================= -->
            
            <a class="navbar-brand" href="./"><img src="<?php echo $TOP_DIR ?>/assets/images/logo.svg" class="logo" alt=""></a>
            
            <!-- ============================================================= LOGO MOBILE : END ============================================================= -->
            
            <a class="btn responsive-menu pull-right" data-toggle="collapse" data-target=".navbar-collapse"><i class='icon-menu-1'></i></a>
            
          </div><!-- /.container -->
        </div><!-- /.navbar-header -->
        
        <div class="yamm">
          <div class="navbar-collapse collapse">
            <div class="container">
              
              <!-- ============================================================= LOGO ============================================================= -->
              
              <a class="navbar-brand" href="./"><img src="<?php echo $TOP_DIR ?>/assets/images/logo.svg" class="logo" alt=""></a>
              
              <!-- ============================================================= LOGO : END ============================================================= -->
              
              
              <!-- ============================================================= MAIN NAVIGATION ============================================================= -->
              
              <ul class="nav navbar-nav">
                
                <li>
                  <a href="minutes">Meetings</a>                  
                </li>
              </ul>
            </div>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.yamm -->
      </div><!-- /.navbar -->
    </header>
    
    <!-- ============================================================= HEADER : END ============================================================= -->
    
